FROM jupyter/minimal-notebook:hub-3.0.0

# Install ngshare_exchange
RUN python3 -m pip install ngshare_exchange --no-cache-dir

# Configure nbgrader
COPY nbgrader_config.py /etc/jupyter/nbgrader_config.py

# That's it!
