FROM jupyterhub/k8s-singleuser-sample:0.9.0-beta.4
USER 0
RUN apt update && apt install -y curl nano
COPY nbgrader_config.py /etc/jupyter/
USER $NB_UID
RUN pip install git+https://github.com/lxylxy123456/nbgrader@exchange_server && \
jupyter nbextension install --symlink --sys-prefix --py nbgrader && \
jupyter nbextension enable --sys-prefix --py nbgrader && \
jupyter serverextension enable --sys-prefix --py nbgrader
