FROM jupyterhub/k8s-singleuser-sample:0.9.0
USER 0
RUN apt update && apt install -y curl nano
COPY nbgrader_config.py /etc/jupyter/
USER $NB_UID
RUN pip install git+https://github.com/lxylxy123456/nbgrader@exchange_server && \
jupyter nbextension install --symlink --sys-prefix --py nbgrader && \
jupyter nbextension enable --sys-prefix --py nbgrader && \
jupyter serverextension enable --sys-prefix --py nbgrader
RUN mkdir /opt/course_management && cd /opt/course_management && curl -O https://raw.githubusercontent.com/lxylxy123456/ngshare/course-management/course_management/README.md -O https://raw.githubusercontent.com/lxylxy123456/ngshare/course-management/course_management/ngshare_management.py -O https://raw.githubusercontent.com/lxylxy123456/ngshare/course-management/course_management/students.csv
