FROM jupyterhub/k8s-singleuser-sample:0.9.0-beta.3.n001.h1cd1311
USER 0
RUN apt update && apt install -y curl
USER $NB_UID
RUN pip install git+https://github.com/rkevin-arch/nbgrader-k8s && \
jupyter nbextension install --symlink --sys-prefix --py nbgrader && \
jupyter nbextension enable --sys-prefix --py nbgrader && \
jupyter serverextension enable --sys-prefix --py nbgrader
