name: Publish to DockerHub and helm repo
on:
  push:
    tags:
      - '*'
jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: libretexts/ngshare:latest
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Install SSH key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.HELM_SSH_KEY }}
          known_hosts: unnecessary
      - run: |
          git config --global user.email "jupyterteam@ucdavis.edu"
          git config --global user.name "ngshare GitHub Actions"
          python3 -m pip install chartpress
          cd helmchart
          chartpress --no-build --publish-chart
