name: Publish to DockerHub and helm repo
on:
  release:
    types: [published]
jobs:
  pypi:
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: user/app:latest
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - run: |
          echo ${HELM_SSH_KEY} > /tmp/ssh_key
          chmod 400 /tmp/ssh_key
          python3 -m pip install chartpress docker==4.2.1
          cd helmchart
          GIT_SSH_COMMAND="ssh -i /tmp/ssh_key" chartpress --push --publish-chart --long
