name: Publish to DockerHub and helm repo
on:
  push:
    tags:
      - '*'
jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Install dependencies
        run: |
          python3 -m pip install chartpress docker==4.2.1
      - name: Install SSH key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.HELM_SSH_KEY }}
          known_hosts: unnecessary
      - name: Run Chartpress
        run: |
          git config --global user.email "jupyterteam@ucdavis.edu"
          git config --global user.name "ngshare GitHub Actions"
          cd helmchart
          echo ${{ secrets.DOCKERHUB_TOKEN }} | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin
          chartpress --push --publish-chart
